GestionFarmacia/Models/Venta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Farmacia.Models
{
    public class Venta
    {
        [Required, Display(Name = "Identificador", Prompt = "Identificador", Description = "Identificador")]
        public int Id { get; set; }

        [Required, Display(Name = "Código", Prompt = "Código", Description = "Código")]
        public string Codigo { get; set; }

        [Required, Display(Name = "Fecha", Prompt = "Fecha", Description = "Fecha")]
        [DataType(DataType.Date)]
        public DateTime Fecha { get; set; }


        [Display(Name = "Total", Prompt = "Total", Description = "Total")]
        [DisplayFormat(DataFormatString = "C$ {0:0.00}", ApplyFormatInEditMode = false)]
        public virtual float Total { get; set; }


        public ICollection<VentaDetalle> VentaDetalles { get; set; }


    }
}

GestionFarmacia/Controllers/VentaDetallesController.cs
using GestionFarmacia.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Farmacia.Models;

namespace GestionFarmacia.Controllers
{
    public class VentaDetallesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: VentaDetalles
        [Authorize(Roles = "Administrador, Regente")]
        public ActionResult Index()
        {
            var ventaDetalles = db.VentaDetalles.Include(v => v.Medicamento).Include(v => v.Venta);
            return View(ventaDetalles.ToList());
        }

        // GET: VentaDetalles/Details/5
        [Authorize(Roles = "Administrador, Regente")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VentaDetalle ventaDetalle = db.VentaDetalles.Find(id);
            if (ventaDetalle == null)
            {
                return HttpNotFound();
            }
            return View(ventaDetalle);
        }

        // GET: VentaDetalles/Create
        [Authorize(Roles = "Administrador, Regente")]
        public ActionResult Create()
        {
            ViewBag.MedicamentoId = new SelectList(db.Medicamentos, "Id", "Nombre");
            ViewBag.VentaId = new SelectList(db.Ventas, "Id", "Codigo");
            return View();
        }

        // POST: VentaDetalles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Regente")]
        public ActionResult Create([Bind(Include = "Id,MedicamentoId,Cantidad,Precio,VentaId")] VentaDetalle ventaDetalle)
        {
            var medicamento = db.Medicamentos.Where(m => m.Id == ventaDetalle.MedicamentoId).Single();

            if (medicamento.Existencia <= 0 || medicamento.Existencia < ventaDetalle.Cantidad ) {

                TempData["error"] = $"La existencia ({medicamento.Existencia}), es menor a la cantidad solicitada({ventaDetalle.Cantidad})";

                ViewBag.MedicamentoId = new SelectList(db.Medicamentos, "Id", "Nombre", ventaDetalle.MedicamentoId);
                ViewBag.VentaId = new SelectList(db.Ventas, "Id", "Codigo", ventaDetalle.VentaId);
                return RedirectToAction("Details", "Ventas", new { @id = ventaDetalle.VentaId});

            }

            if (ModelState.IsValid) {
                db.VentaDetalles.Add(ventaDetalle);
                db.SaveChanges();
                ReducirExitencia(medicamento, ventaDetalle);
                return RedirectToAction("Details", "Ventas", new { @id = ventaDetalle.VentaId });
                
            }


            ViewBag.MedicamentoId = new SelectList(db.Medicamentos, "Id", "Nombre", ventaDetalle.MedicamentoId);
            ViewBag.VentaId = new SelectList(db.Ventas, "Id", "Codigo", ventaDetalle.VentaId);
            return View(ventaDetalle);      
        }

        private void ReducirExitencia(Medicamento medicamento, VentaDetalle ventaDetalle)
        {
            medicamento.Existencia = medicamento.Existencia - ventaDetalle.Cantidad;
            db.Entry(medicamento).State = EntityState.Modified;
            db.SaveChanges();
        }

        // GET: VentaDetalles/Edit/5
        [Authorize(Roles = "Administrador, Regente")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VentaDetalle ventaDetalle = db.VentaDetalles.Find(id);
            if (ventaDetalle == null)
            {
                return HttpNotFound();
            }
            ViewBag.MedicamentoId = new SelectList(db.Medicamentos, "Id", "Nombre", ventaDetalle.MedicamentoId);
            ViewBag.VentaId = new SelectList(db.Ventas, "Id", "Codigo", ventaDetalle.VentaId);
            return View(ventaDetalle);
        }

        // POST: VentaDetalles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Regente")]
        public ActionResult Edit([Bind(Include = "Id,MedicamentoId,Cantidad,Precio,VentaId")] VentaDetalle ventaDetalle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ventaDetalle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MedicamentoId = new SelectList(db.Medicamentos, "Id", "Nombre", ventaDetalle.MedicamentoId);
            ViewBag.VentaId = new SelectList(db.Ventas, "Id", "Codigo", ventaDetalle.VentaId);
            return View(ventaDetalle);
        }

        // GET: VentaDetalles/Delete/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VentaDetalle ventaDetalle = db.VentaDetalles.Find(id);
            if (ventaDetalle == null)
            {
                return HttpNotFound();
            }
            return View(ventaDetalle);
        }

        // POST: VentaDetalles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult DeleteConfirmed(int id)
        {
            VentaDetalle ventaDetalle = db.VentaDetalles.Find(id);
            db.VentaDetalles.Remove(ventaDetalle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionFarmacia/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Farmacia.Models;
using GestionFarmacia.Models;

namespace GestionFarmacia.Controllers
{
    //[Authorize]
    public class VentasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Ventas
        [Authorize(Roles = "Administrador, Regente")]
        public ActionResult Index()
        {
            return View(db.Ventas.ToList());
        }

        // GET: Ventas/Details/5
        [Authorize(Roles = "Administrador, Regente")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Venta venta = db.Ventas.Find(id);
            Venta venta = db.Ventas.Include(m => m.VentaDetalles.Select(x => x.Medicamento)).Where(m => m.Id == id).Single();
            ViewBag.total = venta.VentaDetalles.Sum(d => (d.Precio * d.Cantidad));

            if (TempData["error"] != null)
            {
                ViewBag.Error = TempData["error"].ToString();
            }
            

            if (venta == null)
            {
                return HttpNotFound();
            }
            ViewBag.MedicamentoId = new SelectList(db.Medicamentos, "Id", "Nombre");
            ViewBag.VentaId = new SelectList(db.Ventas, "Id", "Codigo");
            venta.Total = ViewBag.total;
            return View(venta);
        }

        // GET: Ventas/Create
        [Authorize(Roles = "Administrador, Regente")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ventas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Regente")]
        public ActionResult Create([Bind(Include = "Id,Codigo,Fecha,Total")] Venta venta)
        {
            if (ModelState.IsValid)
            {
                db.Ventas.Add(venta);
                db.SaveChanges();
                return RedirectToAction("Details", new { @id = venta.Id});
            }

            return View(venta);
        }

        // GET: Ventas/Edit/5
        [Authorize(Roles = "Administrador, Regente")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venta venta = db.Ventas.Find(id);
            if (venta == null)
            {
                return HttpNotFound();
            }
            return View(venta);
        }

        // POST: Ventas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Regente")]
        public ActionResult Edit([Bind(Include = "Id,Codigo,Fecha,Total")] Venta venta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(venta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(venta);
        }

        // GET: Ventas/Delete/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venta venta = db.Ventas.Find(id);
            if (venta == null)
            {
                return HttpNotFound();
            }
            return View(venta);
        }

        // POST: Ventas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult DeleteConfirmed(int id)
        {
            Venta venta = db.Ventas.Find(id);
            db.Ventas.Remove(venta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionFarmacia/Views/Ventas/Create.cshtml
@model Farmacia.Models.Venta

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Venta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionFarmacia/Views/Ventas/CreateDetalle.cshtml
@model Farmacia.Models.VentaDetalle

@{
    Layout = null;
}


@{
    var id = ViewContext.RouteData.Values["id"];
}


<!-- Modal -->
<div id="modalAddProduct" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Agregar Item</h4>
            </div>
            <div class="modal-body">




                @using (Html.BeginForm("Create", "VentaDetalles", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                       
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.MedicamentoId, "MedicamentoId", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("MedicamentoId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.MedicamentoId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <input type="hidden" name="VentaId" value="@id" />

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Agregar" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>

    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionFarmacia/Views/Ventas/Delete.cshtml
@model Farmacia.Models.Venta

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to Eliminar this?</h3>
<div>
    <h4>Venta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GestionFarmacia/Views/Ventas/Details.cshtml
@model Farmacia.Models.Venta

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles de la venta </h2>
@if (ViewBag.Error != null)
{
    <div class="alert alert-warning">
        <strong>Error</strong> @ViewBag.Error
    </div>
}


<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            Total
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>


    <table class="table">
        <thead class="" style="background-color: black; color: lightgray">
            <tr>
                <th>Cantidad</th>
                <th>Medicamento</th>
                <th>Precio</th>
                <th>Sub Total</th>
                <th><a id="addItemBtn" data-toggle="modal" data-target="#modalAddProduct" href="#" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span></a></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var venta in Model.VentaDetalles)
            {
                <tr>
                    <td>@venta.Cantidad</td>
                    <td>@venta.Medicamento.Nombre</td>
                    <td>@Html.DisplayFor(model => venta.Precio)</td>
                    <td>@Html.DisplayFor(model => venta.SubTotal)</td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", "VentaDetalles", new { id = venta.Id }, null) |
                        @Html.ActionLink("Detalles", "Details", "VentaDetalles", new { id = venta.Id }, null) |
                        @Html.ActionLink("Eliminar", "Delete", "VentaDetalles", new { id = venta.Id }, null)
                    </td>

                </tr>
            }

        </tbody>
    </table>


</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>


@Html.Partial("CreateDetalle", new Farmacia.Models.VentaDetalle())





@section scripts {
    <script type="text/javascript">
        let $addItemBtn = document.getElementById('addItemBtn')
        console.log($addItemBtn)


    </script>
}

GestionFarmacia/Views/Ventas/Edit.cshtml
@model Farmacia.Models.Venta

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Venta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionFarmacia/Views/Ventas/Index.cshtml
@model IEnumerable<Farmacia.Models.Venta>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
       
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>